trigger:
- main  # Set the branch you want to trigger the pipeline on

jobs:
- job: Build  # Renamed the job to 'Build'
  displayName: 'Build Job'
  pool:
    vmImage: 'Amazonlinux-latest'
  steps:
    # your steps here

- job: Test
  displayName: 'Test Job'
  dependsOn: Build  # Corrected dependency reference
  steps:
  - script: |
      # Set up your test steps here
      # For example, running unit tests
      dotnet test --configuration Release
    displayName: 'Run Tests'

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: Test
  steps:
  - script: |
      # Set up your deployment steps here
      # For example, deploying to Azure App Service
      az webapp deployment --name <YourAppName> --resource-group <YourResourceGroup> --src-path '$(Build.ArtifactStagingDirectory)/<PathToYourArtifact>'
    displayName: 'Deploy to Azure'

