trigger:
- main  # Set the branch you want to trigger the pipeline on

pool:
  vmImage: 'windows-latest'  # You can choose a different agent based on your requirements

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
  - script: |
      # Set up your build steps here
      # For example, restoring dependencies and building the project
      dotnet restore
      dotnet build --configuration Release
    displayName: 'Build'

- job: Test
  displayName: 'Test Job'
  dependsOn: Build
  steps:
  - script: |
      # Set up your test steps here
      # For example, running unit tests
      dotnet test --configuration Release
    displayName: 'Run Tests'

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: Test
  steps:
  - script: |
      # Set up your deployment steps here
      # For example, deploying to Azure App Service
      az webapp deployment --name <YourAppName> --resource-group <YourResourceGroup> --src-path '$(Build.ArtifactStagingDirectory)/<PathToYourArtifact>'
    displayName: 'Deploy to Azure'
